import { Inter,  } from "next/font/google";
import Navbar from "@/component/navbar";
import HomeSection from "@/component/home-section"
import CardHome from "@/component/card-home"

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}
      <Navbar></Navbar>
      <HomeSection></HomeSection>
      <CardHome></CardHome>

      </body>
    </html>
  );
}
